/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2017-09-02 15:12:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.LocalDateTime;

public final class default_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

String s=null,s1=null,s2=null,s3=null; 
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.time.LocalDateTime");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\r\n");
      out.write("<title>Library Services</title>\r\n");
      out.write("<link rel=\"icon\" href=\"images/icon1.png\" />\r\n");
      out.write("<link rel=\"alternate stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\"/>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\" />\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\"/>\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"css/materialize.min.css\"  media=\"screen,projection\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function scrollTo1(){ \r\n");
      out.write("document.getElementById('container1').scrollIntoView(true);\r\n");
      out.write("window.scrollBy(0, -36);\r\n");
      out.write("}\r\n");
      out.write("function scrollTo2(){\r\n");
      out.write("document.getElementById('container2').scrollIntoView();\r\n");
      out.write("window.scrollBy(0, -36);\r\n");
      out.write("}\r\n");
      out.write("function scrollTo3(){\r\n");
      out.write("\tdocument.getElementById('social').scrollIntoView();\r\n");
      out.write("\t}\r\n");
      out.write("function changePlaceHolder(){\r\n");
      out.write("var s=document.getElementById('selectClass');\r\n");
      out.write("if(s.value==\"name\"){\r\n");
      out.write("document.getElementsByName('Text1')[0].value='';\r\n");
      out.write("document.getElementsByName('Text1')[0].placeholder='Enter Book Name';\r\n");
      out.write("document.getElementsByName('Text1')[0].title='Name';\r\n");
      out.write("document.getElementsByName('Text1')[0].onkeypress=function myfunction(){\r\n");
      out.write("    return event.charCode >= 32 && event.charCode <= 125;\r\n");
      out.write("}\r\n");
      out.write("document.getElementsByName('Text1')[0].maxLength='40';\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("else if(s.value==\"id\"){\r\n");
      out.write("document.getElementsByName('Text1')[0].value='';\r\n");
      out.write("document.getElementsByName('Text1')[0].placeholder='Enter ID';\r\n");
      out.write("document.getElementsByName('Text1')[0].title='ID';\r\n");
      out.write("document.getElementsByName('Text1')[0].onkeypress=function myfunction(){\r\n");
      out.write("    return event.charCode >= 48 && event.charCode <=57;\r\n");
      out.write("}\r\n");
      out.write("document.getElementsByName('Text1')[0].maxLength='6';\r\n");
      out.write("}\r\n");
      out.write("else if(s.value==\"author\"){\r\n");
      out.write("document.getElementsByName('Text1')[0].value='';\r\n");
      out.write("document.getElementsByName('Text1')[0].placeholder='Enter Author\\'s Name';\r\n");
      out.write("document.getElementsByName('Text1')[0].title='Author';\r\n");
      out.write("document.getElementsByName('Text1')[0].onkeypress=function myfunction(){\r\n");
      out.write("    return event.charCode >= 32 && event.charCode <= 125;\r\n");
      out.write("}\r\n");
      out.write("document.getElementsByName('Text1')[0].maxLength='40';\r\n");
      out.write("}\r\n");
      out.write("else if(s.value==\"publisher\"){\r\n");
      out.write("document.getElementsByName('Text1')[0].value='';\r\n");
      out.write("document.getElementsByName('Text1')[0].placeholder='Enter Publisher\\'s Name';\r\n");
      out.write("document.getElementsByName('Text1')[0].title='Publisher';\r\n");
      out.write("document.getElementsByName('Text1')[0].onkeypress=function myfunction(){\r\n");
      out.write("    return event.charCode >= 32 && event.charCode <= 125;\r\n");
      out.write("}\r\n");
      out.write("document.getElementsByName('Text1')[0].maxLength='40';\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("else if(s.value==\"pubyear\"){\r\n");
      out.write("document.getElementsByName('Text1')[0].value='';\r\n");
      out.write("document.getElementsByName('Text1')[0].placeholder='Enter Year Of Publication';\r\n");
      out.write("document.getElementsByName('Text1')[0].title='Year of Publication';\r\n");
      out.write("document.getElementsByName('Text1')[0].maxLength='4';\r\n");
      out.write("document.getElementsByName('Text1')[0].onkeypress=function myfunction(){\r\n");
      out.write("    return event.charCode >= 48 && event.charCode <= 57;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("else if(s.value==\"category\"){\r\n");
      out.write("document.getElementsByName('Text1')[0].value='';\r\n");
      out.write("document.getElementsByName('Text1')[0].placeholder='Enter Category';\r\n");
      out.write("document.getElementsByName('Text1')[0].title='Category';\r\n");
      out.write("document.getElementsByName('Text1')[0].onkeypress=function myfunction(){\r\n");
      out.write("    return event.charCode >= 32 && event.charCode <= 125;\r\n");
      out.write("}\r\n");
      out.write("document.getElementsByName('Text1')[0].maxLength='40';\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("function alert_root(){\r\n");
      out.write("\talert(\"Access Root to Change the password!\");\r\n");
      out.write("\tmodal.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("onload=function(){\r\n");
      out.write("\tvar e=document.getElementById(\"refreshed\");\r\n");
      out.write("\tif(e.value==\"no\")e.value=\"yes\";\r\n");
      out.write("\telse{e.value=\"no\";location.reload();}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("\tfont-family: \"Yu Gothic UI Light\";\r\n");
      out.write("\tfont-size: medium;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tfont-style: normal;\r\n");
      out.write("\tline-height: 0px;\r\n");
      out.write("\tpadding:0;\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\toverflow-x:hidden;\r\n");
      out.write("\tbackground:#595959;\r\n");
      out.write("}\r\n");
      out.write("body::-webkit-scrollbar{\r\n");
      out.write("\twidth:4px;\r\n");
      out.write("\tbackground-color:grey;\r\n");
      out.write("\tborder-radius:50px;\r\n");
      out.write("}\r\n");
      out.write("body::-webkit-scrollbar-track {\r\n");
      out.write("    box-shadow:10px 10px white;\r\n");
      out.write("    }\r\n");
      out.write("body::-webkit-scrollbar-thumb {\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  outline: 1px solid slategrey;\r\n");
      out.write("  border-radius:50px;\r\n");
      out.write(" \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".MainNavBar{\r\n");
      out.write("\tbackground-color:#333;\r\n");
      out.write("\theight:80px;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\ttop:-1px;\r\n");
      out.write("\tpadding:0;\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\ttop:-14px;\r\n");
      out.write("\tbox-shadow:1px 4px #e24a4a;\r\n");
      out.write("\tborder-radius:0 0 50px 50px;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".title {\r\n");
      out.write("\tmargin: 1px;\r\n");
      out.write("\theight:45px;\r\n");
      out.write("\tfont-family: \"Yu Gothic UI Light\";\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tfont-style: normal;\r\n");
      out.write("\ttext-transform: none;\r\n");
      out.write("\tfont-variant: small-caps;\r\n");
      out.write("\tline-height: normal;\r\n");
      out.write("\tbackground-color: #333;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".toolbar {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tmargin-left:0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\twidth:inherit;\r\n");
      out.write("\theight:35px;\r\n");
      out.write("\tbackground-color: #333;\r\n");
      out.write("    overflow:hidden;\r\n");
      out.write("    position:fixed;\r\n");
      out.write("    top:0px;\r\n");
      out.write("    border-radius:2px;\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write(".toolbar a {\r\n");
      out.write("    float: left;\r\n");
      out.write("    display: block;\r\n");
      out.write("    color: #f2f2f2;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 14px 16px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write(".toolbar a:hover {\r\n");
      out.write("    background-color: #ddd;\r\n");
      out.write("    color: black;\r\n");
      out.write("    box-shadow: 3px 3px 2px grey;\r\n");
      out.write("}\r\n");
      out.write(".toolbar a.active {\r\n");
      out.write("    background-color: #4CAF50;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write(".toolbar-right{\r\n");
      out.write("float:right;\r\n");
      out.write("}\r\n");
      out.write(".container1{\r\n");
      out.write("\tbackground-color: #333;\r\n");
      out.write("\theight:480px;\r\n");
      out.write("\tmargin-top:1px;\r\n");
      out.write("\tmargin-bottom:0;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\ttop:-14px;\r\n");
      out.write("\tmarrgin-top:-20px;\r\n");
      out.write("\tbox-shadow:1px 3px 2px #e24a4a;\r\n");
      out.write("\tborder-radius:50px;\r\n");
      out.write("}\r\n");
      out.write(".container1 img{\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\twidth:640px;\r\n");
      out.write("\theight:100%;\r\n");
      out.write("\tmargin-bottom:10px;\r\n");
      out.write("\tborder-radius:0px 50px 50px 0px;\r\n");
      out.write("\tvertical-align:top;\r\n");
      out.write("\tpadding:0;\r\n");
      out.write("}\r\n");
      out.write(".container1 h1{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write(".container1 p{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tfont-size:15px;\r\n");
      out.write("}\r\n");
      out.write(".container1 br{\r\n");
      out.write("\tfloat:left\r\n");
      out.write("}\r\n");
      out.write(".container-inside{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\twidth:200px;\r\n");
      out.write("\theight:100%;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".container-inside h1{\r\n");
      out.write("    float:left;\r\n");
      out.write("    padding:40px;\r\n");
      out.write("\twidth:800px;\r\n");
      out.write("\tfont-size:25px;\r\n");
      out.write("\tmargin-left:125px;\r\n");
      out.write("    text-align:justify;\r\n");
      out.write("}\r\n");
      out.write(".container-inside p{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\twidth:800px;\r\n");
      out.write("\tfont-size:20px;\r\n");
      out.write("\t\r\n");
      out.write("\tpadding-left:40px;\r\n");
      out.write("\tmargin-left:75px;\r\n");
      out.write("}\r\n");
      out.write(".container-inside a{\r\n");
      out.write("\twidth:100px;\r\n");
      out.write("\tmargin-left:148px;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("}\r\n");
      out.write(".container-inside button{\r\n");
      out.write("\twidth:200px;\r\n");
      out.write("\theight:60px;\r\n");
      out.write("\tbackground:#333;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tborder-style:double;\r\n");
      out.write("\tborder-radius:35px;\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("\tmargin-left:34px;\r\n");
      out.write("\tfont-family:\"Yu Gothic UI Light\";\r\n");
      out.write("\tfont-size:medium;\r\n");
      out.write("\tbox-shadow:1px 3px 2px #e24a4a;\r\n");
      out.write("}\r\n");
      out.write(".container-inside button:hover{\r\n");
      out.write("\tbackground-color:white;\r\n");
      out.write("\tcolor:#333;\r\n");
      out.write("\tfont-weight:900;\r\n");
      out.write("}\r\n");
      out.write(".container2{\r\n");
      out.write("\tfloat:none;\r\n");
      out.write("\tbackground-image:url(images/search_books.jpg) ;\r\n");
      out.write("\tbackground-position:center;\r\n");
      out.write("\tbackground-color:#333;\r\n");
      out.write("\tbackground-repeat:inherit;\r\n");
      out.write("\theight:610px;\r\n");
      out.write("\tmargin-top:1px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tposition:static;\r\n");
      out.write("\tvertical-align:top;\r\n");
      out.write("\tposition:static;\r\n");
      out.write("\ttop:-14px;\r\n");
      out.write("\tbox-shadow:1px 3px 2px #e24a4a;\r\n");
      out.write("\tborder-radius:50px;\r\n");
      out.write("}\r\n");
      out.write(".container2 h1{\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write(".container2 p{\r\n");
      out.write("\tfont-size:15px;\r\n");
      out.write("\theight:30px;\r\n");
      out.write("}\r\n");
      out.write("form{\r\n");
      out.write("\tpadding:0px;\r\n");
      out.write("\tbackground:#333;\r\n");
      out.write("\tborder-radius:75px;\r\n");
      out.write("\tmargin-left:375px;\r\n");
      out.write("\tmargin-right:375px;\r\n");
      out.write("\tbox-shadow:1px 3px 2px #e24a4a;\r\n");
      out.write("}\r\n");
      out.write("form h1{\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tfont-size:24px;\r\n");
      out.write("}\r\n");
      out.write(".form_header{\r\n");
      out.write("\tbackground-color:#666666;\r\n");
      out.write("\theight: 75px;\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tpadding:0;\r\n");
      out.write("\tborder-radius: 75px 75px 0px 0px;\r\n");
      out.write("}\r\n");
      out.write(".bottom_back{\r\n");
      out.write("\tbackground-color:#666666;\r\n");
      out.write("\theight: 75px;\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tpadding:0;\r\n");
      out.write("\tborder-radius: 0px 0px 75px 75px;\r\n");
      out.write("}\r\n");
      out.write("input{\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tbackground-color:#333;\r\n");
      out.write("\twidth:288px;\r\n");
      out.write("\theight:40px;\r\n");
      out.write("\tfont-family:\"Yu Gothic UI Light\";\r\n");
      out.write("\tfont-size:18px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tmargin-left:2px;\r\n");
      out.write("\tborder:thin;\r\n");
      out.write("\tpadding-left: 12px;\r\n");
      out.write("\tborder-radius:10px;\r\n");
      out.write("}\r\n");
      out.write(".submit{\r\n");
      out.write("\tborder:thick;\r\n");
      out.write("\twidth:146px;\r\n");
      out.write("\theight:45px;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\televation:lower;\r\n");
      out.write("\tbackground-color:#333;\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("\tmargin-top:5px;\r\n");
      out.write("}\r\n");
      out.write(".submit:hover{\r\n");
      out.write("\tbackground-color:white;\r\n");
      out.write("\tcolor:#333;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("}\r\n");
      out.write(".reset{\r\n");
      out.write("\tborder:thick;\r\n");
      out.write("\twidth:146px;\r\n");
      out.write("\theight:45px;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\televation:higher;\r\n");
      out.write("\tbackground-color:#333;\r\n");
      out.write("\tcursor:pointer;\r\n");
      out.write("\tmargin-top:5px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".reset:hover{\r\n");
      out.write("\tbackground-color:white;\r\n");
      out.write("\tcolor:#333;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("}\r\n");
      out.write(".selectClass{\r\n");
      out.write("\tbackground:#333;\r\n");
      out.write("\twidth:300px;\r\n");
      out.write("\theight:40px;\r\n");
      out.write("\tfont-family:\"Yu Gothic UI Light\";\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tfont-size:16px;\r\n");
      out.write("\tborder-radius:10px;\r\n");
      out.write("}\r\n");
      out.write(".form_middle{\r\n");
      out.write("\tbackground-color:#666666;\r\n");
      out.write("\tmargin:25px;\r\n");
      out.write("\tborder-radius:100px;\r\n");
      out.write("}\r\n");
      out.write("option{\r\n");
      out.write("\tfont-family:\"Yu Gothic UI Light\";\r\n");
      out.write("\tfont-size:17px;\r\n");
      out.write("\tpadding:12px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.fa {\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    font-size: 30px;\r\n");
      out.write("    width: 30px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    border-radius:50%;\r\n");
      out.write("}\r\n");
      out.write(".fa:hover {\r\n");
      out.write("    opacity: 0.7;\r\n");
      out.write("}\r\n");
      out.write(".fa-facebook {\r\n");
      out.write("    background: #3B5998;\r\n");
      out.write("    color: white;\r\n");
      out.write("    margin-right:3px;\r\n");
      out.write("}\r\n");
      out.write(".fa-linkedin{\r\n");
      out.write("\tbackground: #007bb6;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tmargin-right:4px;\r\n");
      out.write("}\r\n");
      out.write(".fa-google{\r\n");
      out.write("\tbackground:#dd4d42;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tmargin-right:4px;\r\n");
      out.write("}\r\n");
      out.write(".social {\r\n");
      out.write("\tbackground-color:#333;\r\n");
      out.write("\tborder-radius:50px 50px 0 0;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:370px;\r\n");
      out.write("}\r\n");
      out.write(".login_input {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 12px 20px;\r\n");
      out.write("    margin: 8px 0;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    border: 2px solid #ccc;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    box-shadow:1px 1px 2px #e24a4a;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submit_button {\r\n");
      out.write("    background-color: #4285f4;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 14px 20px;\r\n");
      out.write("    margin: 8px 0;\r\n");
      out.write("    border: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    font-family:\"Yu Gothic UI Light\";\r\n");
      out.write("    font-size:18px;\r\n");
      out.write("    font-weight:700;\r\n");
      out.write("    box-shadow:1px 1px 2px #e24a4a;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("    opacity: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cancelbtn {\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("    width:100%;\r\n");
      out.write("    margin:10% auto 10% 0;\r\n");
      out.write("    padding: 10px 18px;\r\n");
      out.write("    text-align:center;\r\n");
      out.write("    font-family:\"Yu Gothic UI Light\";\r\n");
      out.write("    background-color: #e84c3d;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    font-size:16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Center the image and position the close button */\r\n");
      out.write(".imgcontainer {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    margin: 24px 0 12px 0;\r\n");
      out.write("    position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("img.avatar {\r\n");
      out.write("    width: 40%;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("    padding: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("span.psw {\r\n");
      out.write("    float: right;\r\n");
      out.write("    padding-top: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* The Modal (background) */\r\n");
      out.write(".modal {\r\n");
      out.write("    display: none; /* Hidden by default */\r\n");
      out.write("    position: fixed; /* Stay in place */\r\n");
      out.write("    z-index: 1; /* Sit on top */\r\n");
      out.write("    left: 0;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    font-family:\"Yu Gothic UI Light\";\r\n");
      out.write("    width: 100%; /* Full width */\r\n");
      out.write("    height: 100%; /* Full height */\r\n");
      out.write("    overflow:hidden; /* Enable scroll if needed */\r\n");
      out.write("    background-color: rgb(0,0,0); /* Fallback color */\r\n");
      out.write("    background-color: rgba(0,0,0,0.85); /* Black w/ opacity */\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* Modal Content/Box */\r\n");
      out.write(".modal-content {\r\n");
      out.write("    background-color: #fefefe;\r\n");
      out.write("    margin: 10% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */\r\n");
      out.write("    border: 1px solid #888;\r\n");
      out.write("    width: 30%; \r\n");
      out.write("    border-radius:10px;\r\n");
      out.write("}\r\n");
      out.write(".close {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    right: 25px;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    color: #000;\r\n");
      out.write("    font-size: 35px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".close:hover,\r\n");
      out.write(".close:focus {\r\n");
      out.write("    color: red;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Add Zoom Animation */\r\n");
      out.write(".animate {\r\n");
      out.write("    -webkit-animation: animatezoom 0.8s;\r\n");
      out.write("    animation: animatezoom 0.8s\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@-webkit-keyframes animatezoom {\r\n");
      out.write("    from {-webkit-transform: scale(0)} \r\n");
      out.write("    to {-webkit-transform: scale(1)}\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("@keyframes animatezoom {\r\n");
      out.write("    from {transform: scale(0)} \r\n");
      out.write("    to {transform: scale(1)}\r\n");
      out.write("}\r\n");
      out.write("@media screen and (max-width: 300px) {\r\n");
      out.write("    span.psw {\r\n");
      out.write("       display: block;\r\n");
      out.write("       float: none;\r\n");
      out.write("    }\r\n");
      out.write("    .cancelbtn {\r\n");
      out.write("       width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write(".title_login{\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("\tfont-size:20px;\r\n");
      out.write("\tmargin-bottom:50px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tbackground:#333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container_3 {\r\n");
      out.write("    padding: 0 16px;\r\n");
      out.write("}\r\n");
      out.write(".container_3::after, .row::after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    clear: both;\r\n");
      out.write("    display: table;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title_1 {\r\n");
      out.write("    color: grey;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".animate {\r\n");
      out.write("    -webkit-animation: animatezoom 1s;\r\n");
      out.write("    animation: animatezoom 1s\r\n");
      out.write("}\r\n");
      out.write(".one_drive{\r\n");
      out.write("padding-left:25px;\r\n");
      out.write("border-radius:5px;\r\n");
      out.write("font-family:\"Yu Gothic UI Light\";\r\n");
      out.write("margin:5px;\r\n");
      out.write("float:left;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

  Cookie[] c=request.getCookies();
try{
 for(int i=0;i<c.length;i++){
	 if(c[i].getName().equals("lib_admin")&&c[i].getMaxAge()!=0){
		s="lib_admin.jsp";
		s2="ADMIN";
	 }
	 else{
		 s="psw_validate.jsp";
		 s2="LIBRARY ADMIN LOGIN";
	 }
 }
 for(int i=0;i<c.length;i++){
	 if(c[i].getName().equals("cl_access")&&c[i].getMaxAge()!=0){
		s1="cl_access.jsp";
		s3=c[i].getValue();
	 }
	 else{
		 s1="access.jsp";
		 s3="ISSUE/RETURNS";
	 }
 }
}
catch(Exception e){
	 s="psw_validate.jsp";
	 s2="LIBRARY ADMIN LOGIN";
	 s1="access.jsp";
	 s3="ISSUE/RETURNS";
	 System.out.println("SESSION STARTED AT:"+LocalDateTime.now());
	 System.out.println("------------------------------------------------------------------------------------------------------------"); 
	 Cookie cookie=new Cookie("HOME","@PROJECT_alpha"); 
	 response.addCookie(cookie);
}
finally{
	System.out.println("HOME PAGE LOADING STARTED AT:"+LocalDateTime.now());
 
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<div class=\"MAIN animate\" style=\"line-height:0;\">\r\n");
      out.write("<div class=\"MainNavBar\">\r\n");
      out.write("<div class=\"toolbar\">\r\n");
      out.write("<a href=\"#\">HOME</a>\r\n");
      out.write("<a onclick=\"scrollTo3()\">ABOUT</a>\r\n");
      out.write("<a href=\"Report_java.pdf\" onClick=\"MyWindow=window.open('Report_java.pdf','MyWindow',width=600,height=300); return false;\">PROJECT REPORT</a>\r\n");
      out.write("<div class=\"toolbar-right\">\r\n");
      out.write("<a onclick=\"scrollTo1()\">");
      out.print(s3 );
      out.write("</a>\r\n");
      out.write("<a onclick=\"scrollTo2()\">SEARCH BOOKS</a>\r\n");
if(s.equals("lib_admin.jsp")){
      out.write("\r\n");
      out.write("<a href=\"");
      out.print(s);
      out.write("\" style=\"width:auto;\">");
      out.print(s2 );
      out.write("</a>\r\n");
}else {
      out.write("\r\n");
      out.write("<a onclick=\"document.getElementById('id01').style.display='block'\" style=\"width:auto;\">LIBRARY ADMIN LOGIN</a>\r\n");
} 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div >\r\n");
      out.write("<div class=\"title\">\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<h1 align=\"center\">ALPHA LIBRARY APPLICATION</h1>\r\n");
      out.write("</div>\r\n");
      out.write("</div><div class=\"container1\" id=\"container1\">\r\n");
      out.write("<img alt=\"\" src=\"images/issue.jpg\"></img>\r\n");
      out.write("<br></br>\r\n");
      out.write("<p></p>\r\n");
      out.write("<p><br></br></p>\r\n");
      out.write("<div class=\"container-inside\">\r\n");
      out.write("<h1>ISSUE/RETURN BOOKS</h1>\r\n");
      out.write("<p>Click Below to Access Issue/Return Portal</p>\r\n");
      out.write("<p></p>\r\n");
      out.write("<a href=\"");
      out.print(s1);
      out.write("\"><button name=\"issue\" title=\"Issue/Return Books\">Click Here</button></a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container2\" id=\"container2\">\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<form class=\"formSignUP\" id=\"search_books\" method=\"get\" action=\"Search.jsp\">\r\n");
      out.write("<div class=\"form_header\">\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<h1>SEARCH BOOKS</h1>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"form_middle\">\r\n");
      out.write("<p></p>\r\n");
      out.write("<p></p>\r\n");
      out.write("<select class=\"selectClass\" id=\"selectClass\" name=\"bookSearch\" onchange=\"changePlaceHolder()\">\r\n");
      out.write("<option id=\"name\" value=\"name\">BOOK NAME</option>\r\n");
      out.write("<option id=\"id\" value=\"id\">BOOK ID</option>\r\n");
      out.write("<option id=\"author\" value=\"author\">AUTHOR</option>\r\n");
      out.write("<option id=\"publisher\" value=\"publisher\">PUBLISHER</option>\r\n");
      out.write("<option id=\"pubyear\" value=\"pubyear\">YEAR OF PUBLICATION</option>\r\n");
      out.write("<option id=\"category\" value=\"category\">CATEGORY</option>\r\n");
      out.write("</select>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("<input name=\"Text1\" id=\"Text1\" type=\"text\" title=\"Leave this Field Empty to view all Available Books\">&nbsp;</input>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("</div>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"bottom_back\">\r\n");
      out.write("<div style=\"text-align:center;\">\r\n");
      out.write("<input  class=\"submit\" name=\"Text7\" type=\"submit\" id=\"Text7\" title=\"Submit\" value=\"Search\"></input>\r\n");
      out.write("<input class=\"reset\" name=\"Text8\" type=\"reset\" id=\"Text8\" title=\"Clear\" ></input>\r\n");
      out.write("</div>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<p></p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"social\" id=\"social\">\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p style=\"margin-left:10px;font-weight:800;font-size:20px;\">&nbsp;&nbsp;&nbsp;&nbsp;<b>Project Developers</b>: Shashank Sharma, Varun S S</p>\r\n");
      out.write("<br></br>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<a href=\"https://1drv.ms/f/s!AhYpn99IW5siy1X1klODcW5XaELL\" style=\"padding:10px;margin-left:20px;font-size:13px;color:white;\" target=\"_blank\">Click Here To Download The Project Files</a>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p style=\"margin-right:20px;font-weight:500;font-size:13px;float:right;color:#a9abad;\"><b>Image Courtesy</b>: Google Images</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p style=\"margin-right:20px;font-weight:500;font-size:13px;float:right;color:#a9abad;\"><b>Icon Courtesy</b>: Icons8 & W3-CSS</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p style=\"margin-right:20px;font-weight:500;font-size:13px;float:right;color:#a9abad;\"><b>Courtesy</b>: Bootstrap Framework</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p style=\"margin-right:20px;font-weight:500;font-size:13px;float:right;color:#a9abad;\"><b>HTML5 Editor</b>: Microsoft Expression Web4</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p style=\"margin-right:20px;font-weight:500;font-size:13px;float:right;color:#a9abad;\"><b>Powered By</b>: XAMPP & Eclipse</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p style=\"margin-right:20px;font-weight:500;font-size:13px;float:right;color:#a9abad;\"><b>Barcode Support: </b>Barcode Scanner by Zxing, Clipbrd</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<a href=\"mailto:alphadev33@gmail.com\" class=\"fa fa-google\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"id01\" class=\"modal\">\r\n");
      out.write("  <form class=\"modal-content animate\" method=\"post\" action=\"psw_validate.jsp\">  \r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    <p class=\"title_login\">Library Admin</p>  \r\n");
      out.write("      <label><b>Username</b></label>\r\n");
      out.write("      <input type=\"text\" placeholder=\"Enter Username\" class=\"login_input\" name=\"uname\" required />\r\n");
      out.write("      <p>&nbsp;</p>\r\n");
      out.write("      <label><b>Password</b></label>\r\n");
      out.write("      <input type=\"password\" placeholder=\"Enter Password\" class=\"login_input\" name=\"psw\" required />\r\n");
      out.write("      <p>&nbsp;</p> \r\n");
      out.write("      <button type=\"submit\" class=\"submit_button\">Login</button>\r\n");
      out.write("      <p></p>\r\n");
      out.write("      <a onclick=\"alert_root()\" style=\"cursor:pointer;font-weight:800;\">Forgot Password?</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\" style=\"background-color:#f1f1f1\">\r\n");
      out.write("      <button type=\"button\" onclick=\"document.getElementById('id01').style.display='none'\" class=\"cancelbtn\">Cancel</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var modal = document.getElementById('id01');\r\n");
      out.write("window.onclick = function(event) {\r\n");
      out.write("    if (event.target == modal) {\r\n");
      out.write("        modal.style.display = \"none\";}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" id=\"refreshed\" value=\"no\"/>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
System.out.println("HOME PAGE LOADING COMPLETE AT:"+LocalDateTime.now());
System.out.println("------------------------------------------------------------------------------------------------------------");} 
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
