/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2017-08-22 14:40:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class lib_005fadmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\">\r\n");
      out.write("<title>Administrator</title>\r\n");
      out.write("<link rel=\"icon\" href=\"images/admin.png\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script> \r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("\tfont-family:\"Yu Gothic UI Light\";\r\n");
      out.write("\toverflow-x:hidden;\r\n");
      out.write("\tpadding-bottom:42px;\r\n");
      out.write("}\r\n");
      out.write("#demo{\r\n");
      out.write("\tbackground:#333;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tfont-family:\"Yu Gothic UI Light\";\r\n");
      out.write("\tpadding:10px;\r\n");
      out.write("\tborder-radius:20px;\r\n");
      out.write("}\r\n");
      out.write("#demo2{\r\n");
      out.write("\tbackground:#333;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tfont-family:\"Yu Gothic UI Light\";\r\n");
      out.write("\tpadding:10px;\r\n");
      out.write("\tborder-radius:20px;\r\n");
      out.write("}\r\n");
      out.write("#demo3{\r\n");
      out.write("\tbackground:#333;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tfont-family:\"Yu Gothic UI Light\";\r\n");
      out.write("\tpadding:10px;\r\n");
      out.write("\tborder-radius:20px;\r\n");
      out.write("}\r\n");
      out.write("input,textarea{\r\n");
      out.write("\tborder-radius:20px;\r\n");
      out.write("\twidth:350px;\r\n");
      out.write("\theight:40px;\r\n");
      out.write("\tpadding:5px;\r\n");
      out.write("\tcolor:black;\r\n");
      out.write("}\r\n");
      out.write("textarea{\r\n");
      out.write("\theight:100px;\r\n");
      out.write("\tresize:none;\r\n");
      out.write("}\r\n");
      out.write(".date_picker{\r\n");
      out.write("width:175px;\r\n");
      out.write("}\r\n");
      out.write(".help-block{\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("}\r\n");
      out.write("legend{\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tfont-family:\"Yu Gothic UI Light\";\r\n");
      out.write("}\r\n");
      out.write(".btn1{\r\n");
      out.write("\tbackground:#333;\r\n");
      out.write("\theight:50px;\r\n");
      out.write("\tfont-size:18px;\r\n");
      out.write("\tborder-radius:20px;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tbox-shadow:1px 3px 2px #e24a4a;\r\n");
      out.write("}\r\n");
      out.write(".btn_sc{\r\n");
      out.write("\tbackground:#41f471;\r\n");
      out.write("\theight:40px;\r\n");
      out.write("\tcolor:black;\r\n");
      out.write("\tmargin-left:2px;\r\n");
      out.write("\twidth:173px;\r\n");
      out.write("\tborder-radius:20px;\r\n");
      out.write("\tfont-size:15px;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".btn_res{\r\n");
      out.write("\tbackground:#f45942;\r\n");
      out.write("\theight:40px;\r\n");
      out.write("\twidth:173px;\r\n");
      out.write("\tmargin-left:2px;\r\n");
      out.write("\tborder-radius:20px;\r\n");
      out.write("\tfont-size:15px;\r\n");
      out.write("\tcolor:black;\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".MainNavBar{\r\n");
      out.write("\tbackground-color:#333;\r\n");
      out.write("\theight:60px;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\ttop:-1px;\r\n");
      out.write("\tpadding:0;\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\ttop:-20px;\r\n");
      out.write("\tbox-shadow:1px 4px #e24a4a;\r\n");
      out.write("\tborder-radius:0 0 50px 50px;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".title {\r\n");
      out.write("\tmargin: 1px;\r\n");
      out.write("\theight:55px;\r\n");
      out.write("\tfont-family: \"Yu Gothic UI Light\";\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("\tfont-style: normal;\r\n");
      out.write("\ttext-transform: none;\r\n");
      out.write("\tfont-variant: small-caps;\r\n");
      out.write("\tline-height: normal;\r\n");
      out.write("\tbackground-color: #333;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tborder-radius:0 0 50px 50px;\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".toolbar {\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\tmargin-left:0px;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("\twidth:inherit;\r\n");
      out.write("\theight:55px;\r\n");
      out.write("\tbackground-color: #333;\r\n");
      out.write("    overflow:hidden;\r\n");
      out.write("    border-radius:2px;\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write(".toolbar a {\r\n");
      out.write("    float: left;\r\n");
      out.write("    display: block;\r\n");
      out.write("    color: #f2f2f2;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 14px 16px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write(".toolbar a:hover {\r\n");
      out.write("    background-color: #ddd;\r\n");
      out.write("    color: black;\r\n");
      out.write("    box-shadow: 3px 3px 2px grey;\r\n");
      out.write("}\r\n");
      out.write(".toolbar a.active {\r\n");
      out.write("    background-color: #4CAF50;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write(".toolbar-right{\r\n");
      out.write("float:right;\r\n");
      out.write("}\r\n");
      out.write(".s_out{\r\n");
      out.write("\tfloat:right;\r\n");
      out.write("\twidth:15%;\r\n");
      out.write("\theight:35px;\r\n");
      out.write("\tborder-radius:20px;\r\n");
      out.write("\tmargin-right:20px;\r\n");
      out.write("\tfont-weight:600;\r\n");
      out.write("\tbackground:#f46242;\r\n");
      out.write("\tcolor:black;\r\n");
      out.write("}\r\n");
      out.write(".all_books{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\twidth:15%;\r\n");
      out.write("\theight:35px;\r\n");
      out.write("\tborder-radius:20px;\r\n");
      out.write("\tmargin-left:20px;\r\n");
      out.write("\tfont-weight:600;\r\n");
      out.write("\tbackground:#5b8fb2;\r\n");
      out.write("\tcolor:black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".bottom_fix{\r\n");
      out.write("\tmin-width:100%; /* Set a default minimum width */\r\n");
      out.write("    margin-left: -50%; /* Divide value of min-width by 2 */\r\n");
      out.write("    background-color: #333; /* Black background color */\r\n");
      out.write("    color: #fff; /* White text color */\r\n");
      out.write("    text-align: left; /* Centered text */\r\n");
      out.write("    border-radius: 20px 20px 0 0; /* Rounded borders */\r\n");
      out.write("    font-family:\"Yu Gothic UI Light\";\r\n");
      out.write("    position: fixed; /* Sit on top of the screen */\r\n");
      out.write("     /* Add a z-index if needed */\r\n");
      out.write("    left: 50%; /* Center the snackbar */\r\n");
      out.write("    bottom: 0px; /* 30px from the bottom */\r\n");
      out.write("    height:40px;\r\n");
      out.write("}\r\n");
      out.write(".bottom_fix1{\r\n");
      out.write("\theight:100%;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tpadding:0;\t\r\n");
      out.write("}\r\n");
      out.write("td{\r\n");
      out.write("\twidth:20%;\r\n");
      out.write("\tfont-size:20px;\r\n");
      out.write("\tborder-radius:10px;\r\n");
      out.write("\ttext-align:center;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\tfont-family:\"Yu Gothic UI Light\";\r\n");
      out.write("\tborder-radius:5px;\r\n");
      out.write("}\r\n");
      out.write("button{\r\n");
      out.write("\tbackground:#333;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:100%;\r\n");
      out.write("\tborder-radius:5px;\r\n");
      out.write("\tfont-family:\"Yu Gothic UI Light\";\r\n");
      out.write("\tfont-size:22px;\r\n");
      out.write("\tborder:none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");

  Cookie[] c=request.getCookies(); 
 for(int i=0;i<c.length;i++){
	 if(c[i].getName().equals("cl_access")){
		c[i].setPath(null);
		c[i].setMaxAge(0);
		response.addCookie(c[i]);
		break;
	 }
 }
 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"MainNavBar\">\r\n");
      out.write("<div class=\"title\">\r\n");
      out.write("<h1 align=\"center\">ALPHA</h1>\r\n");
      out.write("</div>\r\n");
String s= "mailto:alphadev33@gmail.com?subject=Change Password[RIT-ADMIN]&body=PasswordChangeRequest%0D%0A%0D%0A[ENTER YOUR CURRENT PASSWORD HERE]%0D%0A%0D%0A[ENTER YOUR NEW PASSWORD HERE]";
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\" style=\"width:100%;\">\r\n");
      out.write("  <button type=\"button\" class=\"btn1\" data-toggle=\"collapse\" data-target=\"#demo\" style=\"width:100%;\" id=\"function1\"><b>Click Here To Add Books</b></button>\r\n");
      out.write("  <div id=\"demo\" class=\"collapse\">\r\n");
      out.write("    <form class=\"form-horizontal\" action=\"addbook\" method=\"post\">\r\n");
      out.write("<fieldset>\r\n");
      out.write("<div style=\"width:50%;\">\r\n");
      out.write("<button type=\"submit\" class=\"btn_sc\">Add Book</button>\r\n");
      out.write("<button type=\"reset\" class=\"btn_res\">Clear</button>\r\n");
      out.write("<a href=\"https://www.barcodesinc.com/generator/index.php?\" target=\"_blank\"><button title=\"Enter Book ID in the form\" type=\"button\" class=\"btn_sc\" style=\"background:#3992d6\">Generate Bar-code</button></a>\r\n");
      out.write("</div>\r\n");
      out.write("<p></p>\r\n");
      out.write("<!-- Form Name -->\r\n");
      out.write("<legend>Add Books To the Library</legend>\r\n");
      out.write("<!-- Text input-->\r\n");
      out.write("<div class=\"control-group\" style=\"float:left;width:50%;\">\r\n");
      out.write("  <label class=\"control-label\" for=\"id\">Book ID</label>\r\n");
      out.write("  <div class=\"controls\">\r\n");
      out.write("    <input id=\"id\" name=\"id\" type=\"text\" placeholder=\"Enter Book ID\" class=\"input-large\" required onkeypress=\"return event.charCode >= 48 && event.charCode <=57;\" maxlength=7>\r\n");
      out.write("    <p class=\"help-block\">Enter 6 Digit Book ID</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Text input-->\r\n");
      out.write("<div class=\"control-group\" style=\"float:right;width:50%\">\r\n");
      out.write("  <label class=\"control-label\" for=\"book_name\">Book Name</label>\r\n");
      out.write("  <div class=\"controls\">\r\n");
      out.write("    <input id=\"name\" name=\"name\" type=\"text\" placeholder=\"Enter Book Name\" class=\"input-xlarge\" required=\"\">\r\n");
      out.write("    <p class=\"help-block\">Enter Complete Book Name</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Text input-->\r\n");
      out.write("<div class=\"control-group\" style=\"float:left;width:50%;\">\r\n");
      out.write("  <label class=\"control-label\" for=\"author\">Author</label>\r\n");
      out.write("  <div class=\"controls\">\r\n");
      out.write("    <input id=\"author\" name=\"author\" type=\"text\" placeholder=\"Enter Author's Name\" class=\"input-xlarge\" required=\"\">\r\n");
      out.write("    <p class=\"help-block\"></p>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Text input-->\r\n");
      out.write("<div class=\"control-group\" style=\"float:right;width:50%\">\r\n");
      out.write("  <label class=\"control-label\" for=\"publisher\">Publisher</label>\r\n");
      out.write("  <div class=\"controls\">\r\n");
      out.write("    <input id=\"publisher\" name=\"publisher\" type=\"text\" placeholder=\"Enter Publisher's Name\" class=\"input-xlarge\" required=\"\">\r\n");
      out.write("    <p class=\"help-block\"></p>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Text input-->\r\n");
      out.write("<div class=\"control-group\" style=\"float:left;width:50%;\">\r\n");
      out.write("  <label class=\"control-label\" for=\"category\">Category</label>\r\n");
      out.write("  <div class=\"controls\">\r\n");
      out.write("    <input id=\"category\" name=\"category\" type=\"text\" placeholder=\"Enter Book's Category\" class=\"input-xlarge\" required=\"\">\r\n");
      out.write("    <p class=\"help-block\">*Preferably Department</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Text input-->\r\n");
      out.write("<div class=\"control-group\" style=\"float:right;width:50%\">\r\n");
      out.write("  <label class=\"control-label\" for=\"pubyear\">Published Year</label>\r\n");
      out.write("  <div class=\"controls\">\r\n");
      out.write("    <input id=\"pubyear\" name=\"pubyear\" type=\"text\" placeholder=\"Enter Published Year\" class=\"input-small\" required onkeypress=\"return event.charCode >= 48 && event.charCode <=57;\" maxlength=4>\r\n");
      out.write("    <p class=\"help-block\"></p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<p class=\"help-block\"></p>\r\n");
      out.write("\r\n");
      out.write("<!-- Textarea -->\r\n");
      out.write("<div class=\"control-group\" style=\"float:left;width:100%;\">\r\n");
      out.write("  <label class=\"control-label\" for=\"link\">Google Books Link</label>\r\n");
      out.write("  <div class=\"controls\">                     \r\n");
      out.write("    <textarea id=\"link\" name=\"link\">https://books.google.com</textarea>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<p><br></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("  <p>&nbsp;</p>\r\n");
      out.write("  <button type=\"button\" class=\"btn1\" data-toggle=\"collapse\" data-target=\"#demo2\" style=\"width:100%;\" id=\"function2\"><b>Add Student Access</b></button>\r\n");
      out.write("  <div id=\"demo2\" class=\"collapse\">\r\n");
      out.write("      <form class=\"form-horizontal\" method=\"post\" action=\"studadd\">\r\n");
      out.write("<fieldset>\r\n");
      out.write("\r\n");
      out.write("<!-- Form Name -->\r\n");
      out.write("<legend>Add Student Access</legend>\r\n");
      out.write("\r\n");
      out.write("<div style=\"width:50%;\">\r\n");
      out.write("<button type=\"submit\" class=\"btn_sc\">Add Student</button>\r\n");
      out.write("<button type=\"reset\" class=\"btn_res\">Reset</button>\r\n");
      out.write("<a href=\"https://www.barcodesinc.com/generator/index.php?\" target=\"_blank\"><button type=\"button\" class=\"btn_sc\" style=\"background:#3992d6\" title=\"Enter USN(Last 6 Characters) in the form\">Generate Bar-code</button></a>\r\n");
      out.write("</div>\r\n");
      out.write("<p></p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Prepended text-->\r\n");
      out.write("<div class=\"control-group\">\r\n");
      out.write("  <label class=\"control-label\" for=\"sid\">Student ID</label>\r\n");
      out.write("  <div class=\"controls\">\r\n");
      out.write("    <div class=\"input-prepend\">\r\n");
      out.write("      <input id=\"sid\" name=\"sid\" value=\"1MS1\" class=\"input-medium\" placeholder=\"Enter Student ID\" type=\"text\" required=\"\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <p class=\"help-block\">University Seat Number</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Text input-->\r\n");
      out.write("<div class=\"control-group\">\r\n");
      out.write("  <label class=\"control-label\" for=\"sname\">Student Name</label>\r\n");
      out.write("  <div class=\"controls\">\r\n");
      out.write("    <input id=\"sname\" name=\"sname\" type=\"text\" placeholder=\"Enter Student Name\" class=\"input-xlarge\" required=\"\">\r\n");
      out.write("    <p class=\"help-block\">Full Name</p>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" <p>&nbsp;</p>\r\n");
      out.write("<button type=\"button\" class=\"btn1\" data-toggle=\"collapse\" data-target=\"#demo3\" style=\"width:100%;\"><b>Click Here To View Records</b></button>\r\n");
      out.write("  <div id=\"demo3\" class=\"collapse\">\r\n");
      out.write("    <form class=\"form-horizontal\" action=\"record_access.jsp\" method=\"get\">\r\n");
      out.write("<fieldset>\r\n");
      out.write("<!-- Form Name -->\r\n");
      out.write("<!-- Text input-->\r\n");
      out.write("<div class=\"control-group\" style=\"float:left;width:50%;\">\r\n");
      out.write("  <label class=\"control-label\" for=\"id\">From Date</label>\r\n");
      out.write("  <div class=\"controls\">\r\n");
      out.write("    <input id=\"id\" name=\"id\" type=\"date\" class=\"date_picker\" placeholder=\"DD-MM-YYYY\" value=\"2017-07-01\"required=\"\">\r\n");
      out.write("    <button type=\"submit\" class=\"btn_sc\">View Records</button>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</fieldset>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\"> window.onload = alertName(); </script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"bottom_fix\">\r\n");
      out.write("<table class=\"bottom_fix1\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td style=\"border-right:1px solid;\r\n");
      out.write("\tborder-left:1px solid;\r\n");
      out.write("\tborder-color:white;\">\r\n");
      out.write("<a href=\"default.jsp\"><button>\r\n");
      out.write("<div>\r\n");
      out.write("<span>HOME</span>\r\n");
      out.write("<img alt=\"\" src=\"images/home.png\" style=\"height:25px;width:25px;vertical-align:center;padding:0;margin-bottom:-2px;\">\r\n");
      out.write("</div>\r\n");
      out.write("</button></a></td>\r\n");
      out.write("<td style=\"border-right:1px solid;\r\n");
      out.write("\tborder-left:1px solid;\r\n");
      out.write("\tborder-color:white;\">\r\n");
      out.write("\t<a href=\"Search.jsp?bookSearch=name&Text1=&Text7=Search\"><button onclick=\"Hello()\">\r\n");
      out.write("\t<div>\r\n");
      out.write("<span>VIEW ALL BOOKS</span>\r\n");
      out.write("<img alt=\"\" src=\"images/allBooks.png\" style=\"height:25px;width:25px;vertical-align:center;padding:0;margin-bottom:-2px;\">\r\n");
      out.write("</div>\r\n");
      out.write("</button></a></td>\r\n");
      out.write("<td></td>\r\n");
      out.write("<td style=\"border-right:1px solid;\r\n");
      out.write("\tborder-left:1px solid;\r\n");
      out.write("\tborder-color:white;font-size:16px;\">\r\n");
      out.write("<a href=\"");
      out.print(s);
      out.write("\" target=\"_blank\"><button onclick=\"Hello()\">\r\n");
      out.write("\t<div>\r\n");
      out.write("<span>CHANGE PASSWORD</span>\r\n");
      out.write("<img alt=\"\" src=\"images/password.png\" style=\"height:25px;width:25px;vertical-align:center;padding:0;margin-bottom:-2px;\">\r\n");
      out.write("</div>\r\n");
      out.write("</button></a>\r\n");
      out.write("</td>\r\n");
      out.write("<td style=\"border-right:1px solid;\r\n");
      out.write("\tborder-left:1px solid;\r\n");
      out.write("\tborder-color:white;\">\r\n");
      out.write("<a href=\"s_out.jsp\"><button>\r\n");
      out.write("<div>\r\n");
      out.write("<span>SIGN OUT</span>\r\n");
      out.write("<img alt=\"\" src=\"images/logout.png\" style=\"height:25px;width:25px;vertical-align:center;padding:0;margin-bottom:-2px;\">\r\n");
      out.write("</div>\r\n");
      out.write("</button></a></td>\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
